<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net40</TargetFramework>
    <AssemblyName>KogamaOfflinePatch</AssemblyName>
    <RootNamespace>KogamaOfflinePatch</RootNamespace>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GameFolder>X</GameFolder> <!--You set it to your path-->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MelonLoader">
      <HintPath>..\libs\MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\libs\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>..\libs\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\libs\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\libs\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\libs\UnityEngine.UnityWebRequestModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UI">
      <HintPath>..\libs\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\libs\UnityEngine.AudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
        <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>..\libs\UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\libs\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MVCommon">
      <HintPath>..\libs\MVCommon.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MVWorldObject">
      <HintPath>..\libs\MVWorldObject.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Photon3Unity3D">
      <HintPath>..\libs\Photon3Unity3D.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>